### ISSUE TITLE
How to handle multiple open requests in write mode?

### ISSUE THREAD

**Issue by Drulex** [Drulex/ele_784#1]
@mukandila We use the semaphore SemBuf to protect write access. By default the semaphore will sleep if unable to be captured, however the lab handout mentions the following: "Toute nouvelle ouverture en écriture sera refusée et un code d’erreur (ENOTTY) sera retourné au demandeur." This means that the user/application will have to retry manually to open in write mode until it succeeds instead of just sleeping until the sem is available. Is this the desired behavior?

**Comment by meistermuka** [comment]
I guess that the result or the open it self will be in a while loop checking for ENOTTY. It'll continue looping until it gets the proper return (0??) and open as O_WRONLY or something similar to that.

From my understanding the SemBuf is used to protect the circularBuffer and not the READ or WRITE functions of the driver. The SemBuf will protect the circularBuffer from simultaneous Read/Write actions. Right?

**Comment by Drulex** [comment]
Ok yes that makes sense.
